[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.migration]
dependsOn = ['build']
cmds = ['npm run db:migrate']

[start]
cmd = 'npm start'
dependsOn = ['migration']
